### ISSUE TITLE
Mention Dell 2209WAf

### ISSUE THREAD

**Issue by w8jcik** [rockowitz/rockowitz.github.io#7]
In https://www.ddcutil.com/monitor_notes section.

Maybe add

```
## Dell 2209WAf

With the display connected to an Intel GPU, the source code of `i915` module needs to be modified to reduce the speed of I2C from 100 kHz to 50 kHz.

It is of course highly impractical to build own kernel for this purpose, but the communication fails with the default speed.

https://github.com/rockowitz/ddcutil/issues/424
```

By the way, did you consider uploading the documentation source code instead of the generated version? It could be built automatically in CI. Then people could suggest changes as Pull Requests.

**Comment by rockowitz** [comment]
I have updated wiki page https://github.com/rockowitz/ddcutil/wiki/Notes-on-Specific-Monitors with your information.  My intent is to move all information about specific monitors from www.ddcutil.com to the wiki, so that any (github) user can post what they have observed, without it having to go through me (work in progress).

I had originally tried to store the documentation source on github, but couldn't get it to work adequately, which is why the pages are built offline (using markdown).   This could be revisited, but it's low on my  TODO list.  I would welcome if someone took this on as a project.

**Comment by rockowitz** [comment]
All monitor information previously on the web site has been migrated to the wiki.

**Comment by w8jcik** [comment]
> I would welcome if someone took this on as a project.

I think I should be able to set it up if you are willing to share the source code. I can try to set it up in my GitHub namespace and then pass it to you if it works. I know for sure how to setup this kind of stuff in GitLab in no time. On GitHub I would need more time to figure it out, but I guess it works in similar way.

**Comment by rockowitz** [comment]
Here's a [link](https://www.dropbox.com/scl/fi/uixl3tw8tohcjlh30yor0/ddcutil_doc.tgz?rlkey=07jclqfzp4oxv8z9sbf1d4ahi&st=mvyipfbr&dl=0) to a tgz copy of the directory containing the mkdocs source and supporting functions.  There's some irrelevant stuff (e.g. directory private).  Let me know of any questions you have.

Thank you for taking on this project.
